### ISSUE TITLE
System.exit is not acceptable in a jenkins plugin.

### ISSUE THREAD

**Issue by GregoireW** [jenkinsci/cerberus-testing-plugin#11]
Just got a jenkins crash... I think it is linked to this line...

https://github.com/jenkinsci/cerberus-testing-plugin/blob/330ffe62cfedc31b0ae15079aee606a9752f7200/src/main/java/org/cerberus/jenkinsci/plugins/executecerberustest/ExecuteCerberusCampaign.java#L234

**Comment by daviddelannoy** [comment]
+ 1 here, jenkins service stops because of campaign failed ...

**Comment by nicodeur** [comment]
Hi, I just draft a new release (https://github.com/jenkinsci/cerberus-testing-plugin/releases/tag/cerberus-testing-1.6.3) who fix this problem.

Use a `System.exit(1)` was a bad idea due to a jenkins pipeline bug who don't close a job when campaign failed. Sorry for the inconvenience cause by it.

This new release will be available on Jenkins Plugin Store in a maximum of 8 hours.
